name: Trigger_warning

on: 
  push:
    branches: branch[master]
    
jobs:
  build:
    name: "mainline"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Display SHA-1 Hash
        run: echo "SHA-1 hash " + ${{ github.sha }}
