name: Trigger_warning

on: 
  push:
    branches: branch[master]
    

jobs:
  build:
    name: "mainline"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v24
      - run: echo ${{ github.sha }}
